[2022-11-18T06:24:36.371+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: jobs_analysis.Create_Tables scheduled__2022-11-16T00:00:00+00:00 [queued]>
[2022-11-18T06:24:36.376+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: jobs_analysis.Create_Tables scheduled__2022-11-16T00:00:00+00:00 [queued]>
[2022-11-18T06:24:36.376+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-18T06:24:36.376+0000] {taskinstance.py:1363} INFO - Starting attempt 3 of 4
[2022-11-18T06:24:36.376+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-18T06:24:36.386+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): Create_Tables> on 2022-11-16 00:00:00+00:00
[2022-11-18T06:24:36.389+0000] {standard_task_runner.py:55} INFO - Started process 7325 to run task
[2022-11-18T06:24:36.392+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'jobs_analysis', 'Create_Tables', 'scheduled__2022-11-16T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/jobs_dag.py', '--cfg-path', '/tmp/tmp5b9h4w1p']
[2022-11-18T06:24:36.393+0000] {standard_task_runner.py:83} INFO - Job 11: Subtask Create_Tables
[2022-11-18T06:24:36.425+0000] {task_command.py:376} INFO - Running <TaskInstance: jobs_analysis.Create_Tables scheduled__2022-11-16T00:00:00+00:00 [running]> on host ip-172-31-2-28.us-west-1.compute.internal
[2022-11-18T06:24:36.457+0000] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=lohitha.vanteru@sjsu.edu
AIRFLOW_CTX_DAG_OWNER=Theinsightco
AIRFLOW_CTX_DAG_ID=jobs_analysis
AIRFLOW_CTX_TASK_ID=Create_Tables
AIRFLOW_CTX_EXECUTION_DATE=2022-11-16T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-16T00:00:00+00:00
[2022-11-18T06:24:36.463+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/airflow/providers/postgres/operators/postgres.py", line 94, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 288, in run
    with closing(self.get_conn()) as conn:
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/airflow/providers/postgres/hooks/postgres.py", line 88, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/airflow/hooks/base.py", line 70, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/airflow/models/connection.py", line 432, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `redshift_tci` isn't defined
[2022-11-18T06:24:36.465+0000] {taskinstance.py:1401} INFO - Marking task as UP_FOR_RETRY. dag_id=jobs_analysis, task_id=Create_Tables, execution_date=20221116T000000, start_date=20221118T062436, end_date=20221118T062436
[2022-11-18T06:24:36.473+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 11 for task Create_Tables (The conn_id `redshift_tci` isn't defined; 7325)
[2022-11-18T06:24:36.482+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-18T06:24:36.498+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
